config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"

  get "/home", to: "home#index", as: "home"
  
  get "/rooms", to: "rooms#index", as: "rooms"
  get "/rooms/:id", to: "rooms#show", as: "room"

  get "/guests", to: "guests#index", as: "guests"
  get "/guests/:id", to: "guests#show", as: "guest"

  get "/reservations", to: "reservations#index", as: "reservations"
  get "/reservations/:id", to: "reservations#show", as: "reservation"

  get "/services", to: "services#index", as: "services"
  get "/services/:id", to: "services#show", as: "service"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guest.rb
class Guest < ApplicationRecord
    has_many :reservations, dependent: :destroy

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
    validates :phone, presence: true
    validates :document_id, presence: true

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :reservation

    validates :reservation_id, presence: true
    validates :nights_subtotal, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :services_subtotal, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :tax, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :total, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :issued_at, presence: true
    validates :status, presence: true

end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :guest
    belongs_to :room

    has_many :service_usages, dependent: :destroy
    has_one :invoice, dependent: :destroy

    validates :code, presence: true, uniqueness: true
    validates :guest_id, presence: true
    validates :room_id, presence: true
    validates :check_in, presence: true
    validates :check_out, presence: true
    validates :status, presence: true
    validates :adults, presence: true
    validates :children, presence: true



    def reservation_status
        "#{code} - #{status}"
    end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :reservations, dependent: :destroy

    validates :number, presence: true, uniqueness: true
    validates :room_type, presence: true
    validates :price, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :status, presence: true

    def type_and_status
        "#{number} - #{room_type} - #{status}"
    end
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :service_usages, dependent: :destroy

    validates :name, presence: true
    validates :price, presence: true, numericality: {greater_than_or_equal_to: 0}
    validates :is_active, presence: true
end

app/models/service_usage.rb
class ServiceUsage < ApplicationRecord
    belongs_to :service
    belongs_to :reservation

    validates :reservation_id, presence: true
    validates :service_id, presence: true
    validates :quantity, presence: true
    validates :used_at, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/guests/index.html.erb
<h1>Guests</h1>

<ul>
    <% @guests.each do |guest|%>
        <li>
            <%= link_to(guest.full_name, guest_path(guest.id)) %>
        </li>
    <% end %>
</ul>

<%= link_to "Back to Home", home_path %>

app/views/guests/show.html.erb
<h1>Guest: <%= @guest.full_name %></h1>

<p>Email: <%= @guest.email %></p>
<p>Phone: <%= @guest.phone %></p>
<p>Document ID: <%= @guest.document_id %></p>
<p>Created at: <%= @guest.created_at %></p>

<%= link_to "Back to Guests", guests_path %>

app/views/home/index.html.erb
<div class="container">
  <h1>Welcome to Peters Place</h1>
  <div class="list-buttons">
    <%= link_to "Rooms", rooms_path, class: "btn btn-primary mb-3" %>
    <%= link_to "Guests", guests_path, class: "btn btn-primary mb-3" %>
    <%= link_to "Reservations", reservations_path, class: "btn btn-primary mb-3" %>
    <%= link_to "Services", services_path, class: "btn btn-primary mb-3" %>
  <div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lab 03" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<ul>
    <% @reservations.each do |reservation|%>
        <li>
            <%= link_to "#{reservation.reservation_status}", reservation_path(reservation.id) %>
        </li>
    <% end %>
</ul>

<%= link_to "Back to Home", home_path %>

app/views/reservations/show.html.erb
<h1>Reservation <%= @reservation.code %></h1>

<p>Guest ID: <%= @reservation.guest_id %></p>
<p>Room ID: <%= @reservation.room_id %></p>
<p>Check-in: <%= @reservation.check_in %></p>
<p>Check-out: <%= @reservation.check_out %></p>
<p>Status: <%= @reservation.status %></p>
<p>Adults: <%= @reservation.adults %></p>
<p>Children: <%= @reservation.children %></p>

<%= link_to "Back to Reservations", reservations_path %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>

<ul>
  <% @rooms.each do |room| %>
    <li>
      <%= link_to "Room #{room.type_and_status}", room_path(room) %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to Home", home_path %>

app/views/rooms/show.html.erb
<h1>Room <%= @room.number %></h1>

<p>Type: <%= @room.room_type %></p>
<p>Status: <%= @room.status %></p>
<p>Price: <%= @room.price %></p>
<p>Created at: <%= @room.created_at %></p>

<%= link_to "Back to Rooms", rooms_path %>

app/views/services/index.html.erb
<h1>Services</h1>

<ul>
  <% @services.each do |service| %>
    <li>
      <%= link_to service.name, service_path(service) %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to Home", home_path %>

app/views/services/show.html.erb
<h1><%= @service.name %></h1>

<p>Price: <%= @service.price %></p>
<p>Active: <%= @service.is_active %></p>
<p>Created at: <%= @service.created_at %></p>

<%= link_to "Back to Services", services_path %>